;;;; Emacs Bookmark Format Version 1 ;;;;
;;; This format is meant to be slightly human-readable;
;;; nevertheless, you probably don't want to edit it.
;;; -*- End Of Bookmark File Format Version Stamp -*-
(#1=(#("自动升级提示" 0 6
      (bmkp-full-record #1#))
    (filename . "/media/main/weiyongqing/project/stock3/web/views/partials/main/index.jade")
    (buffer-name . "index.jade")
    (front-context-string . "\n        .modal-")
    (rear-context-string . "          //todo")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(21852 19257 794573 394000))
    (created . #2#)
    (position . 6261))
#1=(#("计算本回合总结数据" 0 9
      (bmkp-full-record #1#))
    (filename . "/media/main/weiyongqing/project/gudoor/src/gudoor/modules/web/app/assets/js/components/round/round.js")
    (buffer-name . "round.js")
    (front-context-string . "      //计算本回合总结数")
    (rear-context-string . "tion (params) {\n")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 2)
    (time 21842 53994 556375 868000)
    (created 21842 52982 242601 282000)
    (position . 16766))
#1=(#("修改最大天数" 0 6
      (bmkp-full-record #1#))
    (filename . "/media/main/weiyongqing/project/gudoor/src/gudoor/modules/web/app/assets/js/components/round/round.js")
    (buffer-name . "round.js")
    (front-context-string . "0,\n        timeS")
    (rear-context-string . "      maxDays: 5")
    (front-context-region-string)
    (rear-context-region-string)
    (visits . 0)
    (time . #2=(21842 52836 377868 329000))
    (created . #2#)
    (position . 517))
)
