;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-word-mode
        beginning-of-buffer
        cua-delete-region
        cua-scroll-down
        describe-key
        duplicate-line
        paredit-forward-delete
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-move
        cua-cancel
        cua-scroll-up
        goto-line
        keyboard-escape-quit
        mouse-buffer-menu
        my-recentf-open
        org-self-insert-command
        previous-buffer
        yas-expand
        ))
